# Generated by Django 5.2.1 on 2026-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='correo electrónico'),
        ),
    ]
