# Generated by Django 5.2.1 on 2026-04-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
