# Generated by Django 5.2.1 on 2026-04-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0002_add_categoria_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='condicion',
            field=models.CharField(blank=True, choices=[('URGENTE', 'Urgente'), ('SURTIDO', 'Surtido'), ('CLIENTE_RETIRA', 'Cliente Retira')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='deposito',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
