# Generated by Django 5.2.1 on 2026-04-18 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0008_pedidoitem_parcial_y_cantidad_back_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('numero_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PREPARANDO', 'Preparando'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('PARCIAL', 'Parcial')], default='PREPARANDO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('despachador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_realizados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='PedidosAlmacen.pedido')),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DespachoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='PedidosAlmacen.despacho')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='PedidosAlmacen.pedidoitem')),
            ],
        ),
    ]
