# Generated by Django 5.2.1 on 2026-04-18 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0009_add_despacho_y_despachoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despachoitem',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despachoitem',
            name='codigo_real',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='despachoitem',
            name='descripcion_real',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='despachoitem',
            name='tipo_incidencia',
            field=models.CharField(blank=True, choices=[('PRODUCTO_ERRONEO', 'Producto Erróneo'), ('SKU_NO_CONTEMPLADO', 'SKU No Contemplado')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='despachoitem',
            name='pedido_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='PedidosAlmacen.pedidoitem'),
        ),
    ]
