# Generated by Django 5.2.1 on 2026-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0011_add_categoria_nombre_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachoitem',
            name='tipo_incidencia',
            field=models.CharField(blank=True, choices=[('PRODUCTO_ERRONEO', 'Producto Erróneo'), ('SKU_NO_CONTEMPLADO', 'SKU No Contemplado'), ('CANTIDAD_MENOR', 'Cantidad Menor a lo Despachado')], default='', max_length=20),
        ),
    ]
