# Generated by Django 5.2.1 on 2026-05-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0015_despacho_picker_pendiente_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
