# Generated by Django 5.2.1 on 2026-05-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0016_add_fecha_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='despachoitem',
            name='foto_incidencia',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/%Y/%m/%d/'),
        ),
    ]
