# Generated by Django 5.2.1 on 2026-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0017_add_foto_incidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachoitem',
            name='tipo_incidencia',
            field=models.CharField(blank=True, choices=[('PRODUCTO_ERRONEO', 'Producto Erróneo'), ('SKU_NO_CONTEMPLADO', 'SKU No Contemplado'), ('CANTIDAD_MENOR', 'Cantidad Menor a lo Despachado'), ('CANTIDAD_MAYOR', 'Cantidad Mayor a lo Despachado')], default='', max_length=20),
        ),
    ]
