# Generated by Django 5.2.1 on 2026-06-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0019_add_traslado_a2_registrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depósito permitido',
                'verbose_name_plural': 'Depósitos permitidos',
                'ordering': ['nombre'],
            },
        ),
    ]
