# Generated by Django 5.2.1 on 2026-06-27 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0020_depositopermitido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despacho',
            name='estado_anterior',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='despacho',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedido',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_anterior',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('PREPARANDO', 'Preparando'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('PARCIAL', 'Parcial'), ('ANULADO', 'Anulado')], default='PREPARANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('PICKING', 'Picking'), ('EN_PREPARACION', 'En Preparación'), ('DESPACHADO', 'Despachado'), ('PARCIAL', 'Parcial'), ('RECIBIDO', 'Recibido'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
    ]
