# Generated by Django 5.2.1 on 2026-07-20 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0022_configuracion_pedidos_y_deposito_transito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionpedidos',
            options={'verbose_name': 'Configuracion deposito tránsito a2', 'verbose_name_plural': 'Configuración de pedidos'},
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DESPACHADO', 'Despachado'), ('PARCIAL', 'Parcial'), ('RECIBIDO', 'Recibido'), ('BACK_ORDER', 'Back Order'), ('INCIDENCIA', 'Incidencia'), ('INCIDENCIA_RESUELTA', 'Incidencia Resuelta')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='ResolucionIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRASLADO', 'Traslado a2'), ('MANUAL', 'Manual')], max_length=10)),
                ('documento_traslado', models.CharField(blank=True, default='', max_length=20)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_resolucion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=255)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resoluciones_anuladas', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolución de incidencia',
                'verbose_name_plural': 'Resoluciones de incidencias',
                'ordering': ['-fecha_resolucion'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('RESOLUCION', 'Resolución'), ('ANULACION', 'Anulación')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.CharField(blank=True, default='', max_length=255)),
                ('despacho_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_incidencia', to='PedidosAlmacen.despachoitem')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_incidencia', to=settings.AUTH_USER_MODEL)),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='PedidosAlmacen.resolucionincidencia')),
            ],
            options={
                'verbose_name': 'Evento de incidencia',
                'verbose_name_plural': 'Eventos de incidencias',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='despachoitem',
            name='resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_resueltos', to='PedidosAlmacen.resolucionincidencia'),
        ),
    ]
