# Generated by Django 5.2.1 on 2026-07-22 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0023_resolucion_incidencias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depositopermitido',
            name='receptores',
            field=models.ManyToManyField(blank=True, help_text='Usuarios autorizados a recibir despachos destinados a este depósito.', related_name='depositos_recepcion', to=settings.AUTH_USER_MODEL),
        ),
    ]
