# Generated by Django 5.2.1 on 2026-07-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0025_grupo_pedidos_receptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='fecha_fin_picking',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='fecha_inicio_picking',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_fin_picking',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_inicio_picking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
