# Generated by Django 5.2.1 on 2026-07-23 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0026_despacho_fecha_fin_picking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cierre',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DESPACHADO', 'Despachado'), ('PARCIAL', 'Parcial'), ('RECIBIDO', 'Recibido'), ('BACK_ORDER', 'Back Order'), ('INCIDENCIA', 'Incidencia'), ('INCIDENCIA_RESUELTA', 'Incidencia Resuelta'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20),
        ),
    ]
