# Generated by Django 5.2.1 on 2026-08-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0028_add_recibido_sin_despachar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='condicion',
            field=models.CharField(blank=True, choices=[('URGENTE', 'Urgente'), ('SURTIDO', 'Surtido'), ('CLIENTE_RETIRA', 'Cliente Retira'), ('INSUMOS', 'Insumos')], default='', max_length=20),
        ),
    ]
