# Generated by Django 5.2.1 on 2026-08-16 15:01

from django.db import migrations, models


def backfill_categoria_items(apps, schema_editor):
    PedidoItem = apps.get_model('PedidosAlmacen', 'PedidoItem')
    for item in PedidoItem.objects.select_related('pedido').filter(categoria=''):
        pedido = item.pedido
        if pedido.categoria:
            item.categoria = pedido.categoria
            item.categoria_nombre = pedido.categoria_nombre
            item.save(update_fields=['categoria', 'categoria_nombre'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0029_add_condicion_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_mixto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='categoria_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunPython(backfill_categoria_items, noop_reverse),
    ]
