# Generated by Django 5.2.1 on 2026-08-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0030_pedido_es_mixto_pedidoitem_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('color_badge', models.CharField(choices=[('danger', 'Rojo'), ('success', 'Verde'), ('info', 'Celeste'), ('secondary', 'Gris'), ('warning', 'Amarillo'), ('primary', 'Azul'), ('dark', 'Oscuro')], default='secondary', max_length=20)),
                ('icono', models.CharField(blank=True, default='', help_text='Clase de Font Awesome, ej. fa-bolt (opcional).', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Condición',
                'verbose_name_plural': 'Condiciones',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='condicion',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
