# Generated by Django 5.2.1 on 2025-08-19 09:21

import django.core.validators
import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_number', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rif_proveedor', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_rif', message='El RIF debe comenzar con J, G, V, E seguido de 9 dígitos.', regex='^[JGVE][0-9]{9}$')])),
                ('header_file', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(null=True, upload_to=tasks.models.Tasks.user_directory_path)),
                ('dbisam_table', models.CharField(blank=True, max_length=100, null=True)),
                ('date_to_execute', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('check_process', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_oferta', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_tasks', to='tasks.tasks')),
            ],
        ),
    ]
