# Generated by Django 5.2.1 on 2025-08-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_productstasks_descripcion'),
    ]

    operations = [
    ]
