# Generated by Django 5.2.1 on 2025-08-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_fecha_ejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_to_execute',
            field=models.DateField(),
        ),
    ]
