# Generated by Django 5.2.1 on 2025-08-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_date_to_execute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='rif_proveedor',
        ),
    ]
