# Generated by Django 5.2.1 on 2025-08-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_tasks_rif_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
