# Generated by Django 5.2.1 on 2025-08-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_is_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_to_execute',
            field=models.DateTimeField(),
        ),
    ]
