# Generated by Django 5.2.1 on 2026-06-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_date_to_execute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEtiquetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('sku', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_items', to='tasks.tasks')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('task', 'orden')},
            },
        ),
    ]
