# Generated by Django 5.2.1 on 2026-08-05 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galpon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('grid_filas', models.PositiveIntegerField(default=10)),
                ('grid_columnas', models.PositiveIntegerField(default=10)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galpones_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('grid_fila', models.PositiveIntegerField(default=1)),
                ('grid_columna', models.PositiveIntegerField(default=1)),
                ('ancho', models.PositiveIntegerField(default=1)),
                ('alto', models.PositiveIntegerField(default=1)),
                ('max_niveles', models.PositiveIntegerField(default=6)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks_creados', to=settings.AUTH_USER_MODEL)),
                ('galpon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='ubicaciones.galpon')),
            ],
            options={
                'ordering': ['galpon', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuerpos_creados', to=settings.AUTH_USER_MODEL)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuerpos', to='ubicaciones.rack')),
            ],
            options={
                'ordering': ['rack', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('cuerpo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='ubicaciones.cuerpo')),
            ],
            options={
                'ordering': ['cuerpo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('PICKING', 'Picking'), ('ALMACENAJE', 'Almacenaje')], default='PICKING', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveles_creados', to=settings.AUTH_USER_MODEL)),
                ('fusionado_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='niveles_fusionados', to='ubicaciones.nivel')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles', to='ubicaciones.ubicacion')),
            ],
            options={
                'ordering': ['ubicacion', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION_GALPON', 'Creación de galpón'), ('EDICION_GALPON', 'Edición de galpón'), ('DESACTIVACION_GALPON', 'Desactivación de galpón'), ('CREACION_RACK', 'Creación de rack'), ('EDICION_RACK', 'Edición de rack'), ('DESACTIVACION_RACK', 'Desactivación de rack'), ('CREACION_CUERPO', 'Creación de cuerpo'), ('DESACTIVACION_CUERPO', 'Desactivación de cuerpo'), ('DESACTIVACION_UBICACION', 'Desactivación de ubicación'), ('EDICION_NIVEL', 'Edición de nivel'), ('DESACTIVACION_NIVEL', 'Desactivación de nivel'), ('ASIGNACION', 'Asignación de producto'), ('EDICION_CANTIDAD', 'Edición de cantidad'), ('DESASIGNACION', 'Desasignación de producto'), ('TRASLADO', 'Traslado entre niveles'), ('FUSION_NIVEL', 'Fusión de niveles'), ('DESFUSION_NIVEL', 'Desfusión de nivel')], db_index=True, max_length=30)),
                ('codigo_producto', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('cuerpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ubicaciones.cuerpo')),
                ('galpon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ubicaciones.galpon')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_ubicacion', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ubicaciones.nivel')),
                ('nivel_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='ubicaciones.nivel')),
                ('nivel_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='ubicaciones.nivel')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ubicaciones.rack')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ubicaciones.ubicacion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProductoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(db_index=True, max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_ubicacion', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='ubicaciones.nivel')),
            ],
            options={
                'ordering': ['codigo_producto'],
                'indexes': [models.Index(fields=['codigo_producto'], name='ubicaciones_codigo__91e44e_idx')],
                'constraints': [models.UniqueConstraint(fields=('codigo_producto', 'nivel'), name='uniq_producto_por_nivel')],
            },
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('galpon', 'codigo'), name='uniq_rack_codigo_por_galpon'),
        ),
        migrations.AddConstraint(
            model_name='cuerpo',
            constraint=models.UniqueConstraint(fields=('rack', 'codigo'), name='uniq_cuerpo_codigo_por_rack'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('cuerpo', 'codigo'), name='uniq_ubicacion_codigo_por_cuerpo'),
        ),
        migrations.AddConstraint(
            model_name='nivel',
            constraint=models.UniqueConstraint(fields=('ubicacion', 'numero'), name='uniq_nivel_numero_por_ubicacion'),
        ),
        migrations.AddIndex(
            model_name='movimientoubicacion',
            index=models.Index(fields=['-fecha'], name='ubicaciones_fecha_889415_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoubicacion',
            index=models.Index(fields=['tipo', '-fecha'], name='ubicaciones_tipo_91a652_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoubicacion',
            index=models.Index(fields=['codigo_producto', '-fecha'], name='ubicaciones_codigo__5c2ca8_idx'),
        ),
    ]
