# Generated by Django 5.2.1 on 2026-05-14 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('max_niveles', models.PositiveIntegerField(blank=True, help_text='Máximo de niveles permitidos (activos + inactivos). Vacío = sin tope.', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('PICKING', 'Picking'), ('ALMACENAJE', 'Almacenaje')], default='PICKING', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveles_creados', to=settings.AUTH_USER_MODEL)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles', to='ubicaciones.rack')),
            ],
            options={
                'ordering': ['rack', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='ubicaciones.nivel')),
            ],
            options={
                'ordering': ['nivel', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProductoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(db_index=True, max_length=50)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_ubicacion', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='ubicaciones.ubicacion')),
            ],
            options={
                'ordering': ['codigo_producto'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION_RACK', 'Creación de rack'), ('EDICION_RACK', 'Edición de rack'), ('DESACTIVACION_RACK', 'Desactivación de rack'), ('CREACION_NIVEL', 'Creación de nivel'), ('EDICION_NIVEL', 'Edición de nivel'), ('DESACTIVACION_NIVEL', 'Desactivación de nivel'), ('CREACION_UBICACION', 'Creación de ubicación'), ('EDICION_UBICACION', 'Edición de ubicación'), ('DESACTIVACION_UBICACION', 'Desactivación de ubicación'), ('ASIGNACION', 'Asignación de producto'), ('DESASIGNACION', 'Desasignación de producto'), ('TRASLADO', 'Traslado entre ubicaciones'), ('FUSION', 'Fusión de ubicaciones')], db_index=True, max_length=30)),
                ('codigo_producto', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_ubicacion', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ubicaciones.nivel')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ubicaciones.rack')),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='ubicaciones.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='ubicaciones.ubicacion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='nivel',
            constraint=models.UniqueConstraint(fields=('rack', 'codigo'), name='uniq_nivel_codigo_por_rack'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('nivel', 'codigo'), name='uniq_ubicacion_codigo_por_nivel'),
        ),
        migrations.AddIndex(
            model_name='productoubicacion',
            index=models.Index(fields=['codigo_producto'], name='ubicaciones_codigo__91e44e_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoubicacion',
            constraint=models.UniqueConstraint(fields=('codigo_producto', 'ubicacion'), name='uniq_producto_por_ubicacion'),
        ),
        migrations.AddIndex(
            model_name='movimientoubicacion',
            index=models.Index(fields=['-fecha'], name='ubicaciones_fecha_889415_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoubicacion',
            index=models.Index(fields=['tipo', '-fecha'], name='ubicaciones_tipo_91a652_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoubicacion',
            index=models.Index(fields=['codigo_producto', '-fecha'], name='ubicaciones_codigo__5c2ca8_idx'),
        ),
    ]
