# Generated by Django 5.2.1 on 2026-09-03 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosAlmacen', '0032_seed_condiciones_existentes'),
        ('ubicaciones', '0002_grupo_pedidos_ubicaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoubicacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimientoubicacion',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoubicacion',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoubicacion',
            name='pedido_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_ubicacion', to='PedidosAlmacen.pedidoitem'),
        ),
        migrations.AddField(
            model_name='movimientoubicacion',
            name='pendiente_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientoubicacion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_ubicacion_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productoubicacion',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimientoubicacion',
            name='tipo',
            field=models.CharField(choices=[('CREACION_GALPON', 'Creación de galpón'), ('EDICION_GALPON', 'Edición de galpón'), ('DESACTIVACION_GALPON', 'Desactivación de galpón'), ('CREACION_RACK', 'Creación de rack'), ('EDICION_RACK', 'Edición de rack'), ('DESACTIVACION_RACK', 'Desactivación de rack'), ('CREACION_CUERPO', 'Creación de cuerpo'), ('DESACTIVACION_CUERPO', 'Desactivación de cuerpo'), ('DESACTIVACION_UBICACION', 'Desactivación de ubicación'), ('EDICION_NIVEL', 'Edición de nivel'), ('DESACTIVACION_NIVEL', 'Desactivación de nivel'), ('ASIGNACION', 'Asignación de producto'), ('EDICION_CANTIDAD', 'Edición de cantidad'), ('DESASIGNACION', 'Desasignación de producto'), ('TRASLADO', 'Traslado entre niveles'), ('FUSION_NIVEL', 'Fusión de niveles'), ('DESFUSION_NIVEL', 'Desfusión de nivel'), ('PICKING', 'Descuento por picking'), ('AJUSTE_A2', 'Ajuste por reconciliación con a2')], db_index=True, max_length=30),
        ),
    ]
